# Generated by Django 5.2.4 on 2025-07-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_business_name_member_membership_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Use {{ membership_number }}, {{ business_name }}, etc.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
