# Generated by Django 5.2.4 on 2025-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use $membership_number, $business_name, $email'),
        ),
    ]
