# Generated by Django 5.2.4 on 2025-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sign_off_text', models.TextField(blank=True)),
                ('signer_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
